set -g mouse on

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1

bind c new-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

set -g history-limit 99999

set -g default-terminal "screen-256color"
set -as terminal-overrides ",xterm*:Tc"
